# .lefthook.yml
pre-commit:
  parallel: true
  commands:
    format:
      run: task format
    check-defaults:
      run: task check-defaults
    lint:
      run: task lint
    deps-verify:
      run: task deps:verify
    test:
      run: task test
