name: CI and Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - "*" # Trigger for all tags

  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.24.x'       # Define Go version here
  YQ_VERSION: '4.34.1'       # Define yq version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Task
        run: |
          INSTALL_DIR="$HOME/.local/bin"
          TASK_INSTALL_SCRIPT_URL="https://taskfile.dev/install.sh"
          mkdir -p "$INSTALL_DIR"
          curl -sL "$TASK_INSTALL_SCRIPT_URL" | sh -s -- -b "$INSTALL_DIR"
          echo "$INSTALL_DIR" >> "$GITHUB_PATH"
        shell: bash

      - name: Display Task Version
        run: task --version

      - name: Install Project Dependencies
        run: task setup

      - name: Run Quality Checks and Upload Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          task check
          bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  release:
    name: Release with GoReleaser
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Only run on tags
    needs: build # Ensure build job is completed successfully

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for changelog generation

      - name: Validate SEMVER Tag
        id: validate_tag
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          echo "Tag: $TAG_NAME"
          if [[ ! "$TAG_NAME" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-([a-zA-Z0-9.-]+))?(\+([a-zA-Z0-9.-]+))?$ ]]; then
            echo "❌ Invalid SEMVER tag: $TAG_NAME"
            exit 1
          fi
          echo "✅ Valid SEMVER tag: $TAG_NAME"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGIE_GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
